
- hosts: perso
  remote_user: fromager
  become_user: root
  become: yes
  vars:
    start_container: '{{ start_container }}'
    build_image: '{{ build_image }}'
    run_map_reduce: '{{run_map_reduce}}'
  tasks:

    - name: build image
      docker_image:
          path: "/home/fromager/Dev/Docker/hadoopdocker"
          name: hadoop
          tag: fred
          state: present
      when: build_image
    - name: remove container
      docker_container:
       name: "hadoop"
       state: absent
      when: start_container

    - name: hadoop container
      docker_container:
       image: "hadoop:fred"
       name: hadoop
       volumes: 
          - /home/fromager/Dev/Docker/hadoopdocker/tp:/tp
          - /home/fromager/Dev/Docker/hadoopdocker/logs:/usr/local/hadoop-2.7.0/logs/userlogs
       ports: "50010:50010,50020:50020,50070:50070,50075:50075,50090:50090,19888:19888,8030:8030,8031:8031,8032:8032,8033:8033,8040:8040,8042:8042,8088:8088,49707:49707,2122:2122"
       state: started
      when: start_container

    - name: run map reduce
      command: docker exec -it hadoop ./start.sh
      when: run_map_reduce
